# Generated by Django 2.1.1 on 2018-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("lc_name", models.CharField(max_length=256)),
                ("logo", models.CharField(max_length=256)),
                ("country", models.CharField(max_length=2)),
                ("alliance", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("parent_code", models.CharField(db_index=True, max_length=3)),
                ("country", models.CharField(max_length=2)),
                ("city", models.CharField(max_length=256)),
                ("longitude", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
                ("train_station", models.BooleanField(default=False)),
                ("bus_station", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("timezone", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=2, primary_key=True, serialize=False
                    ),
                ),
                ("iso_code", models.CharField(db_index=True, max_length=3)),
                ("name", models.CharField(max_length=256)),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("Africa", "AFRICA"),
                            ("Asia", "ASIA"),
                            ("Caribbean", "CARIBBEAN"),
                            ("North America", "NORTH_AMERICA"),
                            ("Central America", "CENTRAL_AMERICA"),
                            ("South America", "SOUTH_AMERICA"),
                            ("Oceania", "OCEANIA"),
                            ("Europe", "EUROPE"),
                        ],
                        max_length=256,
                    ),
                ),
                ("dialingCode", models.CharField(max_length=6)),
            ],
        ),
    ]
