# Generated by Django 2.1.1 on 2018-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=None, to="resources.Country"
            ),
        )
    ]
